# Generated by Django 4.2.16 on 2024-10-31 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
