# Generated by Django 4.2 on 2024-11-24 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0003_listitem_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="list",
            name="title_text",
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="list",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="listitem",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="listitem",
            name="list",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="list",
                to="todo.list",
            ),
        ),
        migrations.AlterField(
            model_name="listtags",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="templateitem",
            name="created_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
