# Generated by Django 4.2 on 2024-11-27 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0004_voicenote"),
    ]

    operations = [
        migrations.AlterField(
            model_name="list",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="list",
            name="updated_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="listitem",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="listtags",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="template",
            name="updated_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="templateitem",
            name="created_on",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
